apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: beatball-cert
  namespace: beatball-game
spec:
  secretName: beatball-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - beatball.xyz