apiVersion: apps/v1
kind: Deployment
metadata:
  name: physics-server
  namespace: beatball-game
  labels:
    app: physics-server
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: physics-server
  template:
    metadata:
      labels:
        app: physics-server
    spec:
      containers:
      - name: physics-server
        image: beatball/physics-server:latest  # Thay your-dockerhub-username bằng username Docker của bạn
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8000"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: physics-server-service
  namespace: beatball-game
  annotations:
    cloud.google.com/app-protocols: '{"ws":"HTTPS","wss":"HTTPS"}'  # Thêm annotation này
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: ws  # Thêm port cho WebSocket
    port: 443
    targetPort: 8000
    protocol: TCP
  selector:
    app: physics-server