apiVersion: apps/v1
kind: Deployment
metadata:
  name: physics-server
  namespace: beatball-game
  labels:
    app: physics-server
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: physics-server
  template:
    metadata:
      labels:
        app: physics-server
    spec:
      containers:
      - name: physics-server
        image: beatball/physics-server:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8000"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: physics-server-service
  namespace: beatball-game
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "beatball-ip"
    cloud.google.com/app-protocols: '{"wss":"HTTPS"}'
    cloud.google.com/backend-config: '{"ports": {"443":"physics-server-backendconfig"}}'
    # Thêm các annotations này
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "physics-server-service"
spec:
  type: LoadBalancer
  ports:
  - name: wss
    port: 443
    targetPort: 8000
    protocol: TCP
  selector:
    app: physics-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  namespace: beatball-game
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "game-managed-cert"
    kubernetes.io/ingress.global-static-ip-name: "beatball-ip"
spec:
  ingressClassName: gce
  rules:
  - host: beatball.xyz  # Thêm host vào đây
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: physics-server-service
            port:
              number: 443
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: physics-server-backendconfig
  namespace: beatball-game
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 300
  healthCheck:
    checkIntervalSec: 15
    port: 8000
    type: HTTP
    requestPath: /health  
  securityPolicy:
    name: "websocket-security-policy"
